"""add calculation model

Revision ID: e0897c2b69e9
Revises: 
Create Date: 2025-11-20 19:23:12.849078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0897c2b69e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('a', sa.Float(), nullable=False),
    sa.Column('b', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('ADD', 'SUB', 'MUL', 'DIV', name='calculation_type'), nullable=False),
    sa.Column('result', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculations_id'), 'calculations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculations_id'), table_name='calculations')
    op.drop_table('calculations')
    # ### end Alembic commands ###
